### ISSUE TITLE
Can’t change things about campfire except on-off

### ISSUE THREAD

**Issue by Rad233** [melontini/m-tweaks#5] opened 2023-02-11 04:57 UTC
Game version: 1.18.2 fabric
Mod version: 0.4.4
Environment: 
1. tweaks-0.4.4-1.18.2
2. fabric-api-0.67.1+1.18.2
3. modmenu-3.2.3
4. cloth-config-6.2.57
Description: 
Can’t change things about campfire except on-off, I tried changing things(like radius) after closing game, but still not working.
Log: 
[latest.log](https://github.com/melontini/m-tweaks/files/10712636/latest.log)

**Comment by melontini** [comment] 2023-02-11 05:04
Ugh, this seems to be an issue with collapsible options. I can't find the culprit.

I can't check ATM, but do other options work fine?

**Comment by Rad233** [comment] 2023-02-11 06:55
> Ugh, this seems to be an issue with collapsible options. I can't find the culprit.
> 
> I can't check ATM, but do other options work fine?

Yes, they works fine

**Comment by melontini** [comment] 2023-02-11 10:50
The problem is probably related to https://github.com/shedaniel/cloth-config/issues/135 
This means we can't have comments in the config

Should be fixed now

**Closed by melontini** 2023-02-11 10:50 UTC
Labels: bug, 1.18
